// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1678884837);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.region.update.updated", 1678466271);
user_pref("browser.search.region", "IT");
user_pref("calendar.caldav.googleResync", 1678466269);
user_pref("calendar.list.sortOrder", "efd47e0e-a2a6-4601-84fb-a53b2011ed0c");
user_pref("calendar.registry.efd47e0e-a2a6-4601-84fb-a53b2011ed0c.calendar-main-default", true);
user_pref("calendar.registry.efd47e0e-a2a6-4601-84fb-a53b2011ed0c.calendar-main-in-composite", true);
user_pref("calendar.registry.efd47e0e-a2a6-4601-84fb-a53b2011ed0c.disabled", true);
user_pref("calendar.registry.efd47e0e-a2a6-4601-84fb-a53b2011ed0c.name", "Home");
user_pref("calendar.registry.efd47e0e-a2a6-4601-84fb-a53b2011ed0c.type", "storage");
user_pref("calendar.registry.efd47e0e-a2a6-4601-84fb-a53b2011ed0c.uri", "moz-storage-calendar://");
user_pref("calendar.timezone.local", "Europe/Rome");
user_pref("calendar.ui.version", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 1);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1678884820170");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1678884810);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230131132728");
user_pref("extensions.lastAppVersion", "102.7.1");
user_pref("extensions.lastPlatformVersion", "102.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"default-theme@mozilla.org\":\"dfb25d1f-860a-4678-90d0-af22c779835a\",\"google@search.mozilla.org\":\"6d9121ce-a100-44fc-944b-03fe8b2e3392\",\"ddg@search.mozilla.org\":\"76207b57-483c-4f58-8aac-c02f72c3a3c9\",\"amazondotcom@search.mozilla.org\":\"10b27687-d1c5-4b50-a661-83b24a202674\",\"wikipedia@search.mozilla.org\":\"d2e36834-eef6-415b-95ca-486663f736d8\",\"bing@search.mozilla.org\":\"763db44c-2446-4473-8b6c-d5ec5d3fd84c\"}");
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.ui-rdf.version", 34);
user_pref("mailnews.database.global.datastore.id", "2e4dfc30-96f9-430c-8788-2c21e5a5576");
user_pref("mailnews.headers.extraAddonHeaders", "autocrypt openpgp");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "102.7.1");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Important");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Work");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "To Do");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Later");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("toolkit.telemetry.cachedClientID", "785c6991-64e3-4800-a488-a1791f93de2d");
user_pref("toolkit.telemetry.previousBuildID", "20230131132728");
